# Generated by Django 3.0.2 on 2020-06-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0002_remove_sites_lasttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
