# Generated by Django 3.0.2 on 2020-06-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0003_auto_20200604_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
