# Generated by Django 3.0.2 on 2020-06-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0004_sites_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='avgOfAll',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sites',
            name='sumOfAll',
            field=models.IntegerField(default=0),
        ),
    ]
