# Generated by Django 3.0.2 on 2020-06-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0006_auto_20200613_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='dailyTime',
            field=models.IntegerField(default=0),
        ),
    ]
