# Generated by Django 3.0.2 on 2020-06-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0007_sites_dailytime'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg', models.FloatField(default=0.0)),
                ('day', models.IntegerField(null=True)),
            ],
        ),
    ]
