# Generated by Django 3.0.2 on 2020-06-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTracker', '0008_weekday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeekDay',
        ),
    ]
